# Generated by Django 5.2 on 2026-05-05 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='pending_journalists',
            field=models.ManyToManyField(blank=True, related_name='pending_publishers', to=settings.AUTH_USER_MODEL),
        ),
    ]
